name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '20'
          registry-url: https://registry.npmjs.org
          scope: '@octocat'
      - run: npm Install

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact (dist)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1